src/Plugins/Nop.Plugin.Payments.AmazonPay/Controllers/AmazonPayCheckoutController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Plugin.Payments.AmazonPay.Enums;
using Nop.Plugin.Payments.AmazonPay.Services;
using Nop.Services.Messages;
using Nop.Web.Controllers;

namespace Nop.Plugin.Payments.AmazonPay.Controllers;

[AutoValidateAntiforgeryToken]
public class AmazonPayCheckoutController : BasePublicController
{
    #region Fields

    private readonly AmazonPayCheckoutService _amazonPayCheckoutService;
    private readonly INotificationService _notificationService;

    #endregion

    #region Ctor

    public AmazonPayCheckoutController(AmazonPayCheckoutService amazonPayCheckoutService,
        INotificationService notificationService)
    {
        _amazonPayCheckoutService = amazonPayCheckoutService;
        _notificationService = notificationService;
    }

    #endregion

    #region Methods

    public async Task<IActionResult> Confirm()
    {
        try
        {
            await _amazonPayCheckoutService.ReadAndSaveCheckoutSessionIdAsync();

            //validation
            var cart = await _amazonPayCheckoutService.GetCartAsync();
            if (!cart.Any())
                return RedirectToRoute("ShoppingCart");

            if (!await _amazonPayCheckoutService.IsAllowedToCheckoutAsync())
                return Challenge();

            //model
            var model = await _amazonPayCheckoutService.PrepareConfirmOrderModelAsync(cart);

            return View("~/Plugins/Payments.AmazonPay/Views/Confirm.cshtml", model);
        }
        catch (Exception exception)
        {
            _notificationService.ErrorNotification(exception.Message);

            return RedirectToRoute("ShoppingCart");
        }
    }

    [HttpPost, ActionName("Confirm")]
    public async Task<IActionResult> ConfirmOrder(string shippingoption)
    {
        try
        {
            //validation
            var cart = await _amazonPayCheckoutService.GetCartAsync();
            if (!cart.Any())
                return RedirectToRoute("ShoppingCart");

            if (!await _amazonPayCheckoutService.IsAllowedToCheckoutAsync())
                return Challenge();

            if (!await _amazonPayCheckoutService.ShoppingCartRequiresShippingAsync(cart))
                await _amazonPayCheckoutService.SetShippingMethodToNullAsync();
            else
            {
                var success = await _amazonPayCheckoutService.SetShippingMethodAsync(cart, shippingoption);

                if (!success)
                    return RedirectToAction("Confirm");
            }

            var scWarnings = await _amazonPayCheckoutService.GetShoppingCartWarningsAsync(cart);
            if (!string.IsNullOrEmpty(scWarnings))
            {
                _notificationService.WarningNotification(string.Join("<br />", scWarnings));

                return RedirectToRoute("ShoppingCart");
            }

            var url = await _amazonPayCheckoutService.UpdateCheckoutSessionAsync();

            return Redirect(url);
        }
        catch (Exception exception)
        {
            _notificationService.ErrorNotification(exception.Message);

            return RedirectToRoute("ShoppingCart");
        }
    }

    [HttpPost]
    public async Task<IActionResult> GetPaymentInfo(int placement)
    {
        var (payload, signature, amount) = await _amazonPayCheckoutService.CreateCheckoutSessionAsync((ButtonPlacement)placement);

        if (string.IsNullOrEmpty(payload))
            return ErrorJson($"{AmazonPayDefaults.PluginSystemName} error: Payload creation failed");

        if (string.IsNullOrEmpty(signature))
            return ErrorJson($"{AmazonPayDefaults.PluginSystemName} error: Signature validation failed");

        return Json(new { payload, signature, amount });
    }

    public async Task<IActionResult> Completed()
    {
        try
        {
            var cart = await _amazonPayCheckoutService.GetCartAsync();
            if (!cart.Any())
                return RedirectToRoute("ShoppingCart");

            var (order, warnings, model) = await _amazonPayCheckoutService.CompleteCheckoutAsync();

            if (order == null)
            {
                if (warnings.Any())
                    _notificationService.WarningNotification(string.Join("<br />", warnings));

                return RedirectToRoute("ShoppingCart");
            }

            return View("~/Plugins/Payments.AmazonPay/Views/Completed.cshtml", model);
        }
        catch (Exception exception)
        {
            _notificationService.ErrorNotification(exception.Message);

            return RedirectToRoute("ShoppingCart");
        }
    }

    #endregion
}

src/Plugins/Nop.Plugin.Payments.AmazonPay/Controllers/AmazonPayCustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Plugin.Payments.AmazonPay.Services;
using Nop.Web.Framework.Controllers;

namespace Nop.Plugin.Payments.AmazonPay.Controllers;

[AutoValidateAntiforgeryToken]
public class AmazonPayCustomerController : BasePaymentController
{
    #region Fields

    private readonly AmazonPayCustomerService _amazonPayCustomerService;

    #endregion

    #region Ctor

    public AmazonPayCustomerController(AmazonPayCustomerService amazonPayCustomerService)
    {
        _amazonPayCustomerService = amazonPayCustomerService;
    }

    #endregion

    #region Methods

    public async Task<IActionResult> SignIn()
    {
        return await _amazonPayCustomerService.SignInAsync();
    }

    [HttpPost]
    public async Task<IActionResult> AssociateOrCreateAccount(string buyerId, string buyerEmail, string buyerName)
    {
        if (await _amazonPayCustomerService.AssociateOrCreateCustomerAsync(buyerId, buyerEmail, buyerName))
            return Json(new { Redirect = true });

        return Json(new { Status = "Ok!" });
    }

    [HttpPost]
    public async Task<IActionResult> SignOut(string buyerId)
    {
        await _amazonPayCustomerService.SignOutAsync(buyerId);

        return Json(new { Status = "Ok!" });
    }

    #endregion
}

src/Plugins/Nop.Plugin.Payments.AmazonPay/Views/ChangeLink.cshtml
@model ChangeLinkModel

<button class="button-1" id="amazon-pay-change-button-@Model.ChangeAction">@T("Plugins.Payments.AmazonPay.Confirm.ChangeButton")</button>

<script asp-location="Footer">
    $(function () {
        amazon.Pay.bindChangeAction('#amazon-pay-change-button-@Model.ChangeAction', {
            amazonCheckoutSessionId: '@Model.CheckoutSessionId',
            changeAction: '@Model.ChangeAction'
        });
    });
</script>

src/Plugins/Nop.Plugin.Payments.AmazonPay/Views/Completed.cshtml
@model CheckoutCompletedModel

@{
    Layout = "~/Views/Shared/_ColumnsOne.cshtml";

    //title
    NopHtml.AddTitleParts(T("PageTitle.Checkout").Text);
    //page class
    NopHtml.AppendPageCssClassParts("html-checkout-page");
    NopHtml.AppendPageCssClassParts("html-order-completed-page");
}

<script src="@Model.AmazonPayScript" asp-location="Footer"></script>

<div class="page checkout-page order-completed-page">
    <div class="page-title">
        <h1>@T("Checkout.ThankYou")</h1>
    </div>
    <div class="page-body checkout-data">
        @await Component.InvokeAsync(typeof(WidgetViewComponent), new { widgetZone = PublicWidgetZones.CheckoutCompletedTop, additionalData = Model })
        <div class="section order-completed">
            <div class="title">
                <strong>@T("Checkout.YourOrderHasBeenSuccessfullyProcessed")</strong>
            </div>
            <div class="details">
                <div class="order-number">
                    <strong>@T("Checkout.OrderNumber"): @Model.CustomOrderNumber</strong>
                </div>
                <div class="details-link">
                    <a href="@Url.RouteUrl("OrderDetails", new { orderID = Model.OrderId })">@T("Checkout.PlacedOrderDetails")</a>
                </div>
            </div>
            <div class="buttons">
                <div><button type="button" class="button-1 order-completed-continue-button" onclick="setLocation('@Url.RouteUrl("Homepage")')">@T("Checkout.ThankYou.Continue")</button></div>
                <div><button id="signout" type="button" class="button-1" style="margin-top: 5px;">@T("Plugins.Payments.AmazonPay.SignIn.SignOutButton")</button></div>
            </div>
        </div>
        @await Component.InvokeAsync(typeof(WidgetViewComponent), new { widgetZone = PublicWidgetZones.CheckoutCompletedBottom, additionalData = Model })
    </div>
</div>

<script asp-location="Footer">
    $(function () {
        var signoutElement = document.getElementById('signout');
        signoutElement.onclick = function () {
            amazon.Pay.signout();
            signOut();
            $(this).hide();
        };
    });

    function signOut() {
        var postData = {
            BuyerId: '@Model.BuyerId'
        };
        addAntiForgeryToken(postData);

        $.ajax({
            cache: false,
            type: 'POST',
            url: '@Url.Action("SignOut", "AmazonPayCustomer")',
            data: postData,
            success: function (data, textStatus, jqXHR) {
                setLocation('@Url.RouteUrl("Homepage")')
            },
        });
    }

</script>	

src/Plugins/Nop.Plugin.Payments.AmazonPay/Views/Confirm.cshtml
@model CheckoutConfirmModel

@{
    Layout = "~/Views/Shared/_ColumnsOne.cshtml";

    //title
    NopHtml.AddTitleParts(T("PageTitle.Checkout").Text);
}

<script src="@Model.AmazonPayScript" asp-location="Footer"></script>

<div class="page checkout-page">
    <div class="page-title">
        <h1>@T("Checkout.ConfirmYourOrder")</h1>
    </div>
    <div class="page-body checkout-data">
        @await Component.InvokeAsync(typeof(WidgetViewComponent), new { widgetZone = PublicWidgetZones.CheckoutConfirmTop })
        <div class="section confirm-order">
            <form asp-controller="AmazonPayCheckout" asp-action="Confirm" method="post" id="confirm-order-form">
                <script asp-location="Footer">
                    $(function () {
                        $('#confirm-order-form').submit(function () {
                            $('input[type=submit]', this).attr('disabled', 'disabled');
                        });
                    });

                    function sendRequest() {
                        var postData = {
                            BuyerId: '@Model.BuyerId',
                            BuyerEmail: '@Model.BuyerEmail',
                            BuyerName: '@Model.BuyerName'
                        };
                        addAntiForgeryToken(postData);

                        $.ajax({
                            cache: false,
                            type: 'POST',
                            url: '@Url.Action("AssociateOrCreateAccount", "AmazonPayCustomer")',
                            data: postData,
                            complete: function (data, textStatus, jqXHR) {
                                $('#associateButton').hide();
                                $('#createButton').hide();
                                if (data.responseJSON.Redirect) {
                                    window.location = '@(Url.RouteUrl("Login", new { returnUrl = webHelper.GetRawUrl(Context.Request) }))';
                                }
                                else {
                                    window.location = window.location.href;
                                }
                            }
                        });
                    }
                </script>
                @if (!string.IsNullOrEmpty(Model.MinOrderTotalWarning))
                {
                    <span class="min-order-warning">@Model.MinOrderTotalWarning</span>
                }
                else
                {
                    <div class="buttons">
                        <input type="submit" name="nextstep" value="@T("Plugins.Payments.AmazonPay.Confirm.PlaceOrder")" class="button-1 confirm-order-next-step-button"/>

                        @if (Model.CanCreateAccount)
                        {
                            <button id="createButton" type="button" class="button-1" onclick="sendRequest()">@T("Plugins.Payments.AmazonPay.SignIn.CreateButton")</button>
                        }
                        @if (Model.CanAssociateAccount)
                        {
                            <button id="associateButton" type="button" class="button-1" onclick="sendRequest()">@T("Plugins.Payments.AmazonPay.SignIn.AssociateButton")</button>
                        }
                    </div>
                }
                @if (Model.Warnings.Count > 0)
                {
                    <div class="message-error">
                        <ul>
                            @foreach (var warning in Model.Warnings)
                            {
                                <li>@warning</li>
                            }
                        </ul>
                    </div>
                }
                else
                {
                    <div hidden="@(!Model.RequiresShipping)">
                        @await Component.InvokeAsync(typeof(WidgetViewComponent), new { widgetZone = PublicWidgetZones.CheckoutShippingMethodTop })
                        <div class="section shipping-method">
                            @if (Model.Warnings.Count == 0)
                            {
                                <ul class="method-list">
                                    @for (var i = 0; i < Model.ShippingMethods.Count; i++)
                                    {
                                        var shippingMethod = Model.ShippingMethods[i];
                                        <li>
                                            <div class="method-name">
                                                <input id="shippingoption_@(i)" type="radio" name="shippingoption" value="@(shippingMethod.Name)___@(shippingMethod.ShippingRateComputationMethodSystemName)" checked="@shippingMethod.Selected" />
                                                <label for="shippingoption_@(i)">@shippingMethod.Name (@shippingMethod.Fee)</label>
                                            </div>
                                            @if (!string.IsNullOrEmpty(shippingMethod.Description))
                                            {
                                                <div class="method-description">
                                                    @Html.Raw(shippingMethod.Description)
                                                </div>
                                            }
                                        </li>
                                    }
                                </ul>
                            }
                        </div>
                        @await Component.InvokeAsync(typeof(WidgetViewComponent), new { widgetZone = PublicWidgetZones.CheckoutShippingMethodBottom })
                    </div>
                }
            </form>
        </div>
        @await Component.InvokeAsync(typeof(WidgetViewComponent), new { widgetZone = PublicWidgetZones.CheckoutConfirmBottom })
        <div class="order-summary-body">
            @await Component.InvokeAsync(typeof(OrderSummaryViewComponent), new { prepareAndDisplayOrderReviewData = true })
        </div>
    </div>
</div>

<script asp-location="Footer">
    //TODO: do something with displaying the order amount
    $(function () {
        $(".cart-footer").hide();
    });

</script>

src/Plugins/Nop.Plugin.Payments.AmazonPay/Views/DoNotUseWithAmazonPay.cshtml
@model DoNotUseWithAmazonPayModel

<nop-card asp-name="amazon-pay" asp-icon="fa fa-amazon" asp-title="Amazon Pay" asp-hide-block-attribute-name="Amazon-Pay" asp-hide="false" asp-advanced="false">
    <div class="card-body">
        <div class="form-group row">
            <div class="col-md-3">
                <nop-label asp-for="DoNotUseWithAmazonPay" />
            </div>
            <div class="col-md-9">
                <nop-editor asp-for="DoNotUseWithAmazonPay" />
            </div>
        </div>
    </div>
</nop-card>

src/Plugins/Nop.Plugin.Payments.AmazonPay/Views/MiniCart.cshtml
@model PaymentInfoModel

@{
    var amazonPayButtonId = $"AmazonPayButton-{Guid.NewGuid().ToString().ToLower()}";
}

<script src="@Model.AmazonPayScript" asp-location="Footer"></script>

<script asp-location="Footer">
    $(function () {

        var targetNode = $(document.getElementById('flyout-cart')).find('.buttons');

        if (targetNode.length == 0) {
            return;
        }

        $(targetNode).append('<div style="margin-top:5px" id="@amazonPayButtonId"></div>');
        var isCartContainsNoAllowedProducts = @Model.IsCartContainsNoAllowedProducts.ToString().ToLower();
        if (isCartContainsNoAllowedProducts) {
            $('#@amazonPayButtonId').html('@Html.Raw(T("Plugins.Payments.AmazonPay.CantUseAmazonPay"))');
            return;
        }

        var amazonPayButton = amazon.Pay.renderButton('#@amazonPayButtonId', {
            merchantId: '@Html.Raw(settings.MerchantId)',
            publicKeyId: '@Html.Raw(settings.PublicKeyId)',
            ledgerCurrency: '@Html.Raw(Model.LedgerCurrency)',
            productType: '@Html.Raw(Model.ProductType)',
            placement: '@Html.Raw(Model.AmazonPayPlacement)',
            buttonColor: '@Html.Raw(Model.ButtonColor)'
        });

        amazonPayButton.onClick(function () {
            var sendRequest = false;
            //terms of service
            if ($('#termsofservice').length > 0) {
                //terms of service element exists
                if (!$('#termsofservice').is(':checked')) {
                    $('#terms-of-service-warning-box').dialog();
                } else {
                    sendRequest = true;
                }
            }
            else {
                if ($('#add-to-cart-button-@Model.ProductId').length > 0) {
                    AddProductToCart(amazonPayButton);
                } else {
                    sendRequest = true;
                }
            }

            if (sendRequest) {
                var postData = {
                    placement: '@((int)Model.Placement)'
                };
                addAntiForgeryToken(postData);

                $.ajax({
                    cache: false,
                    type: 'POST',
                    url: '@(Url.Action("GetPaymentInfo", "AmazonPayCheckout"))',
                    data: postData,
                    success: function (data, textStatus, jqXHR) {
                        if (data.error) {
                            alert(data.error);
                        }
                        else {
                            amazonPayButton.initCheckout({
                                estimatedOrderAmount: { 'amount': data.amount, 'currencyCode': '@Html.Raw(Model.Currency)' },
                                createCheckoutSessionConfig: {
                                    payloadJSON: data.payload,
                                    signature: data.signature,
                                    algorithm: 'AMZN-PAY-RSASSA-PSS-V2',
                                    publicKeyId: '@Html.Raw(settings.PublicKeyId)'
                                }
                            });
                        }
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        alert(errorThrown);
                    }
                });
            }
        });
    });
</script>

src/Plugins/Nop.Plugin.Payments.AmazonPay/Views/PaymentInfo.cshtml
@model PaymentInfoModel

@{
    var amazonPayButtonId = $"AmazonPayButton-{Guid.NewGuid().ToString().ToLower()}";
    var description = Model.Placement == ButtonPlacement.Checkout || Model.Placement == ButtonPlacement.PaymentMethod
        ? null
        : T("Plugins.Payments.AmazonPay.CheckoutWithAmazon").Text;
}

<script src="@Model.AmazonPayScript" asp-location="Footer"></script>

<style type="text/css">
    div.pay-with-amazon {
        max-width: 450px
    }

    div.pay-with-amazon ul {
        text-align: left;
        list-style: disc;
        padding: 20px 0 30px 0;
        font-size: 80%;
    }

    div.pay-with-amazon h2 {
        text-align: @(Model.Placement == ButtonPlacement.Product ? "left" : "center");
        padding-top: @(Model.Placement == ButtonPlacement.Product ? "10px" : "0px");
    }
</style>

<div id="amazonPayDescription"></div>
<div><div style='@(Model.Placement == ButtonPlacement.Product ? "width: 195px; max-width: 195 px; display: inline-block;" : "");margin:0 auto;' id="@amazonPayButtonId"></div></div>

@{
    if (Model.Placement == ButtonPlacement.Checkout)
        await Html.PartialAsync("~/Plugins/Payments.AmazonPay/Views/_Checkout.cshtml", amazonPayButtonId);
}

<script asp-location="Footer">
    $(function () {

        var isCartContainsNoAllowedProducts = @Model.IsCartContainsNoAllowedProducts.ToString().ToLower();
        if (isCartContainsNoAllowedProducts) {
            $('#@amazonPayButtonId').html('@Html.Raw(T("Plugins.Payments.AmazonPay.CantUseAmazonPay"))');
            return;
        }

        var nextButton = $('button.button-1.payment-info-next-step-button');
        if (nextButton.length > 0) {
            nextButton.hide();
        }

        var amazonPayButton = amazon.Pay.renderButton('#@amazonPayButtonId', {
            merchantId: '@Html.Raw(settings.MerchantId)',
            publicKeyId: '@Html.Raw(settings.PublicKeyId)',
            ledgerCurrency: '@Html.Raw(Model.LedgerCurrency)',
            productType: '@Html.Raw(Model.ProductType)',
            placement: '@Html.Raw(Model.AmazonPayPlacement)',
            buttonColor: '@Html.Raw(Model.ButtonColor)'
        });

        if (amazonPayButton) {
            $('#amazonPayDescription').html(`@Html.Raw(description)`);
        }

        amazonPayButton.onClick(function () {
            var sendRequest = false;

            //terms of service
            if ($('#termsofservice').length > 0) {
                //terms of service element exists
                if (!$('#termsofservice').is(':checked')) {
                    $('#terms-of-service-warning-box').dialog();
                } else {
                    sendRequest = true;
                }
            }
            else {
                if ($('#add-to-cart-button-@Model.ProductId').length > 0) {
                    AddProductToCart(amazonPayButton);
                } else {
                    sendRequest = true;
                }
            }

            if (sendRequest) {
                StartCheckout(amazonPayButton);
            }
        });
    });

    function AddProductToCart(amazonPayButton) {

        var urladd = '@Url.RouteUrl("AddProductToCart-Details", new { productId = Model.ProductId, shoppingCartTypeId = (int)ShoppingCartType.ShoppingCart })';

        if (AjaxCart.loadWaiting !== false) {
            return;
        }
        AjaxCart.setLoadWaiting(true);

        $.ajax({
            cache: false,
            url: urladd,
            data: $('#product-details-form').serialize(),
            type: 'POST',
            success: (response) => success_process(response, amazonPayButton),
            complete: AjaxCart.resetLoadWaiting,
            error: AjaxCart.ajaxFailure
        });
    }

    function StartCheckout(amazonPayButton) {
        var postData = {
            placement: '@((int)Model.Placement)'
        };
        addAntiForgeryToken(postData);

        $.ajax({
            cache: false,
            type: 'POST',
            url: '@(Url.Action("GetPaymentInfo", "AmazonPayCheckout"))',
            data: postData,
            success: function (data, textStatus, jqXHR) {
                if (data.error) {
                    alert(data.error);
                }
                else {
                    amazonPayButton.initCheckout({
                        estimatedOrderAmount: { 'amount': data.amount, 'currencyCode': '@Html.Raw(Model.Currency)' },
                        createCheckoutSessionConfig: {
                            payloadJSON: data.payload,
                            signature: data.signature,
                            algorithm: 'AMZN-PAY-RSASSA-PSS-V2',
                            publicKeyId: '@Html.Raw(settings.PublicKeyId)'
                        }
                    });
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert(errorThrown);
            }
        });
    }

    function success_process(response, amazonPayButton) {

        var redirect = false;
        if (response.redirect) {
            response.redirect = '';
            redirect = true;
        }

        AjaxCart.success_process(response);

        if ((response.message && response.success === true) || redirect) {
            StartCheckout(amazonPayButton)
        }

        return false;
    }

</script>

src/Plugins/Nop.Plugin.Payments.AmazonPay/Views/SignIn.cshtml
@model SignInModel

<script src="@Model.AmazonPayScript" asp-location="Footer"></script>

<div style="margin:0 auto;" id="amazonPayButton"></div>

<script asp-location="Footer">
    $(function () {

        amazon.Pay.renderButton('#amazonPayButton', {
            // set checkout environment
            merchantId: '@Html.Raw(settings.MerchantId)',
            ledgerCurrency: '@Html.Raw(Model.LedgerCurrency)',
            sandbox: Boolean('@settings.UseSandbox'),
            productType: 'SignIn',
            placement: 'Other',
            buttonColor: '@Html.Raw(Model.ButtonColor)',
            // configure sign in
            signInConfig: {
                payloadJSON: '@Html.Raw(Model.Payload)',
                signature: '@Html.Raw(Model.Signature)',
                algorithm: 'AMZN-PAY-RSASSA-PSS-V2',
                publicKeyId: '@Html.Raw(settings.PublicKeyId)'
            }
        });
    });
</script>

src/Plugins/Nop.Plugin.Payments.AmazonPay/Views/_Checkout.cshtml
@model string

<script asp-location="Footer">
    $(function () {

        // Select the node that will be observed for mutations
        const targetNode = document.getElementById('checkout-steps');

        // Options for the observer (which mutations to observe)
        const config = { attributes: true, childList: false, subtree: true };

        // Callback function to execute when mutations are observed
        const callback = (mutationList, observer) => {
            var pos = $('.tab-section.active').find('span.number').text();
            button = $('#@Model');

            if (button == underfine)
                return;

            if (pos == underfinde || pos == 1)
            {
                button.show();
                return;
            }

            button.hide();
        };

        // Create an observer instance linked to the callback function
        const observer = new MutationObserver(callback);

        // Start observing the target node for configured mutations
    });
</script>